### ISSUE TITLE
Why we don't use the sst2 dataset from GLUE benchmark?

### ISSUE THREAD

**Issue by JacksonWuxs** [HKUNLP/ProGen#3]
Dear Authors,

I am very interesting your series of works about generating datasets under a zero-shot setting. 
Once I reviewed your code, I have one question is that why we shift to GPT-3mix/sst2 dataset instead of the originally glue/sst2 data?
The code is at https://github.com/HKUNLP/ProGen/blob/main/tasks/tc_processor.py#L20. 

Best,
Xuansheng

**Comment by jiacheng-ye** [comment]
Hi, Xuansheng, sorry for the late reply. Thanks for your question!
We choose GPT-3mix/sst2 because the sentences in the original glue/sst2 dataset are segment level, meaning they are not complete sentences. As we generate dataset with complete sentences, we thus adopt GPT-3mix/sst2 for evaluation.

**Comment by JacksonWuxs** [comment]
Yeah, it makes sense to me. Thanks!
